[package]
name = "library_standard_numbers"
version = "0.1.0"
edition = "2021"
authors = ["Max Kadel <mkadel@princeton.edu>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
